version: '3'
services:
    database:
        build: 
            context: ./services-docker/mysql/
            dockerfile: Dockerfile
        ports:
        - "3306:3306"
    api:
        build:
            context: ./
            dockerfile: ./services-docker/nodejs/Dockerfile
        ports:
        - "3000:3000"
        depends_on:
        - database
        environment:
        - DATABASE_HOST=database-verretech
        volumes:
        - ./api-verretech
    

