version: '3.6'

services:
    security:
    build: ./services-docker/nodejs
    ports:
     - "3000:3000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./verre-tech/api:/app/api
    db:
        build: ./services-docker/mysql
       
   